# ##############################################################################
# .appveyor.yml
#
# Appveyor CI integration file
# 
# Copyright Chris Glover 2014-2015
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt
#
# ##############################################################################

environment:
  matrix:
    - GENERATOR: "Visual Studio 12"
      CONFIG: Debug
      VS_VERSION: "12.0"

    - GENERATOR: "Visual Studio 12"
      CONFIG: Release
      VS_VERSION: "12.0"

    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Debug
      VS_VERSION: "12.0"

    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Release
      VS_VERSION: "12.0"

test_script:
  - ps: cd _builds
  - cmd: ctest -VV -C "%CONFIG%"

build_script:
  - cmd: call "C:/Program Files (x86)/Microsoft Visual Studio %VS_VERSION%/Common7/Tools/vsvars32.bat"
  - cmd: cmake --version
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIG% ..
  - cmd: cmake --build .