language: cpp

script: cmake

git:
    submodules: false

compiler:
 - clang
 - gcc

env:
  global:
    - GCC_VERSION="4.9"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
    - ASAN=On

matrix:
  exclude:
    - compiler: gcc
      env: ASAN=On
    - compiler: clang
      env: GCC_VERSION="4.9"
    - compiler: gcc
      env: BUILD_TYPE=Debug

# Install dependencies
before_install:
  - export CHECKOUT_PATH=`pwd`;
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  # Used foer determining the boost verion on the machine
  #- sudo apt-get install aptitude
  #- aptitude search libboost
  - export BOOST_VERSION="1.55"
  - sudo apt-get install libboost-thread${BOOST_VERSION}-dev libboost-chrono${BOOST_VERSION}-dev libboost-date-time${BOOST_VERSION}-dev libboost-system${BOOST_VERSION}-dev libboost-test${BOOST_VERSION}-dev libboost-timer${BOOST_VERSION}-dev #libboost1.55-all-dev
  - sudo apt-get install -qq g++-${GCC_VERSION}
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

install:
  - cd $CHECKOUT_PATH
  - if [ ! -d build ]; then mkdir build; fi
  - cd build
  - export CXX_FLAGS=""
  - export CXX_LINKER_FLAGS=""
  - if [ -z "$BUILD_TYPE" ]; then export BUILD_TYPE=Release; fi
  - if [ -n "$ASAN" ]; then export CXX_FLAGS="${CXX_FLAGS} -fsanitize=address,undefined,integer -fno-omit-frame-pointer -fno-sanitize=unsigned-integer-overflow"; fi
  - if [ "$CXX" == "clang++" ]; then CXX_FLAGS="${CXX_FLAGS} -D__extern_always_inline=inline"; fi

  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENTITY_ENABLE_PERFORMANCE_TESTS=OFF -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_EXE_LINKER_FLAGS="-Wl,--no-as-needed ${CXX_LINKER_FLAGS} -lrt"
  - make VERBOSE=1
script:
  - ctest -VV