entity: entity::component_destruction_queue< ComponentPool > Singleton Reference
entity::component_destruction_queue< ComponentPool > Singleton Reference
Description
template<typename ComponentPool>
singleton entity::component_destruction_queue< ComponentPool >
Definition at line 29 of file component_destruction_queue.hpp.
Public Types
typedef ComponentPool::type type
Public Member Functions
void clear ()
component_destruction_queue (ComponentPool &p)
void flush ()
void push (weak_entity e)
~component_destruction_queue ()
Member Function Documentation
template<typename ComponentPool > void entity::component_destruction_queue< ComponentPool >::clear ()
Definition at line 56 of file component_destruction_queue.hpp.
Referenced by entity::component_destruction_queue< ComponentPool >::flush().
         {
             destroyed_.clear();
         }
template<typename ComponentPool > void entity::component_destruction_queue< ComponentPool >::flush ()
Definition at line 49 of file component_destruction_queue.hpp.
References entity::component_destruction_queue< ComponentPool >::clear().
Referenced by entity::component_destruction_queue< ComponentPool >::~component_destruction_queue().
         {
             std::sort(destroyed_.begin(), destroyed_.end(), std::greater<weak_entity>());
             pool_.destroy_range(destroyed_.begin(), destroyed_.end());
             clear();
         }
template<typename ComponentPool > void entity::component_destruction_queue< ComponentPool >::push (weak_entity e)
Definition at line 44 of file component_destruction_queue.hpp.
         {
             destroyed_.push_back(e);
         }
Member Typedef Documentation
template<typename ComponentPool > typedef ComponentPool::type entity::component_destruction_queue< ComponentPool >::type
Definition at line 33 of file component_destruction_queue.hpp.
Constructor & Destructor Documentation
template<typename ComponentPool > entity::component_destruction_queue< ComponentPool >::component_destruction_queue (ComponentPool & p)
Definition at line 35 of file component_destruction_queue.hpp.
             : pool_(p)
         {}
template<typename ComponentPool > entity::component_destruction_queue< ComponentPool >::~component_destruction_queue ()
Definition at line 39 of file component_destruction_queue.hpp.
References entity::component_destruction_queue< ComponentPool >::flush().
         {
             flush();
         }