entity: entity::entity_pool Class Reference
entity::entity_pool Class Reference
Description
Definition at line 48 of file entity_pool.hpp.
Instances and minimal complete definitions
struct signal_list
Public Types
typedef iterator_impl const_iterator
typedef iterator_impl iterator
Public Member Functions
iterator begin () const
entity create ()
shared_entity create_shared ()
unique_entity create_unique ()
void destroy (entity e)
bool empty () const
iterator end () const
entity_pool ()
signal_list & signals ()
std::size_t size () const
~entity_pool ()
Member Function Documentation
iterator entity::entity_pool::begin () const
Definition at line 174 of file entity_pool.hpp.
Referenced by entity::begin(), entity::component::dense_pool< T >::dense_pool(), and entity::component::sparse_pool< T >::sparse_pool().
         {
             return iterator_impl(0);
         }
entity entity::entity_pool::create ()
Definition at line 109 of file entity_pool.hpp.
References entity::make_entity(), entity::entity_pool::signal_list::on_entity_create, and signals().
         {
             entity_index_t* new_idx = new(entity_pool_.malloc()) entity_index_t(entities_.size());
             entity ret_val = make_entity(*new_idx);
             entities_.push_back(new_idx);
             signals().on_entity_create(ret_val);
             return ret_val;
         }
shared_entity entity::entity_pool::create_shared ()
Definition at line 154 of file entity_pool.hpp.
References create_unique().
         {
             return create_unique();
         }
unique_entity entity::entity_pool::create_unique ()
Definition at line 118 of file entity_pool.hpp.
References entity::make_entity(), entity::entity_pool::signal_list::on_entity_create, and signals().
Referenced by create_shared().
         {
             entity_index_t* new_idx_ptr = nullptr;
             void* new_index_mem = nullptr;
             bool pop_on_catch = false;
             try
             {
                 new_index_mem = entity_pool_.malloc();
                 new_idx_ptr = new(new_index_mem) entity_index_t(entities_.size());
                 entity ent_val = make_entity(*new_idx_ptr);
                 entities_.push_back(new_idx_ptr);
                 // Ensure we leave the container in a good state if shared_ptr throws.
                 pop_on_catch = true;
                 unique_entity::ref_type new_idx(
                     new_idx_ptr,
                     entity_deleter(*this)
                 );
                 signals().on_entity_create(ent_val);
                 return std::move(new_idx);
             }
             catch(...)
             {
                 if(pop_on_catch)
                     entities_.pop_back();
                 if(new_idx_ptr)
                     new_idx_ptr->~entity_index_t();
                 if(new_index_mem)
                     entity_pool_.free(new_index_mem);
                 throw;
             }
         }
void entity::entity_pool::destroy (entity e)
Definition at line 159 of file entity_pool.hpp.
Referenced by ~entity_pool().
         {
             destroy_impl(e.index());
         }
bool entity::entity_pool::empty () const
Definition at line 169 of file entity_pool.hpp.
         {
             return entities_.empty();
         }
iterator entity::entity_pool::end () const
Definition at line 179 of file entity_pool.hpp.
References size().
Referenced by entity::component::dense_pool< T >::dense_pool(), entity::end(), and entity::component::sparse_pool< T >::sparse_pool().
         {
             return iterator_impl(size());
         }
signal_list& entity::entity_pool::signals ()
Definition at line 184 of file entity_pool.hpp.
Referenced by entity::component::sparse_pool< T >::auto_create_components(), entity::component::saturated_pool< T >::auto_create_components(), entity::component::dense_pool< T >::auto_create_components(), create(), create_unique(), entity::component::dense_pool< T >::dense_pool(), entity::component::saturated_pool< T >::saturated_pool(), and entity::component::sparse_pool< T >::sparse_pool().
         {
             return signals_;
         }
std::size_t entity::entity_pool::size () const
Definition at line 164 of file entity_pool.hpp.
Referenced by entity::component::dense_pool< T >::dense_pool(), end(), and entity::component::saturated_pool< T >::saturated_pool().
         {
             return entities_.size();
         }
Member Typedef Documentation
typedef iterator_impl entity::entity_pool::const_iterator
Definition at line 88 of file entity_pool.hpp.
typedef iterator_impl entity::entity_pool::iterator
Definition at line 87 of file entity_pool.hpp.
Constructor & Destructor Documentation
entity::entity_pool::entity_pool ()
Definition at line 97 of file entity_pool.hpp.
             : entity_pool_(16)
         {}
entity::entity_pool::~entity_pool ()
Definition at line 101 of file entity_pool.hpp.
References destroy(), and entity::make_entity().
         {
             while(!entities_.empty())
             {
                 destroy(make_entity(*entities_.back()));
             }
         }