entity: entity::sparse_component_pool< T > Class Template Reference
entity::sparse_component_pool< T > Class Template Reference
Description
template<typename T>
class entity::sparse_component_pool< T >
Definition at line 54 of file sparse_component_pool.hpp.
Instances and minimal complete definitions
struct window
Friends
class component_creation_queue< sparse_component_pool< T > >
class component_destruction_queue< sparse_component_pool< T > >
Public Types
typedef iterator_impl iterator
typedef T type
Public Member Functions
void auto_create_components (entity_pool &owner_pool, T const &default_value)
iterator begin ()
T * create (entity e, type original)
void destroy (entity e)
iterator end ()
T * get (entity e)
T const * get (entity e) const
std::size_t size ()
sparse_component_pool (entity_pool &owner_pool, T const &default_value=T())
window view ()
Methods
template<typename T > friend class component_creation_queue< sparse_component_pool< T > > friend
Definition at line 298 of file sparse_component_pool.hpp.
template<typename T > friend class component_destruction_queue< sparse_component_pool< T > > friend
Definition at line 299 of file sparse_component_pool.hpp.
Member Function Documentation
template<typename T > void entity::sparse_component_pool< T >::auto_create_components (entity_pool & owner_pool, T const & default_value)
Definition at line 219 of file sparse_component_pool.hpp.
References entity::sparse_component_pool< T >::create(), entity::entity_pool::signal_list::on_entity_create, and entity::entity_pool::signals().
         {
             slots_.entity_create_handler =
                 owner_pool.signals().on_entity_create.connect(
                     boost::bind(
                         &sparse_component_pool::create,
                         this,
                         ::_1,
                         default_value
                     )
                 )
             ;
         }
template<typename T > iterator entity::sparse_component_pool< T >::begin ()
Definition at line 276 of file sparse_component_pool.hpp.
         {
             return iterator(components_.begin());
         }
template<typename T > T* entity::sparse_component_pool< T >::create (entity e, type original)
Definition at line 242 of file sparse_component_pool.hpp.
Referenced by entity::sparse_component_pool< T >::auto_create_components(), and entity::sparse_component_pool< T >::sparse_component_pool().
         {
             auto r = components_.emplace(e, std::move(original));
             return &(r.first->second);
         }
template<typename T > void entity::sparse_component_pool< T >::destroy (entity e)
Definition at line 249 of file sparse_component_pool.hpp.
         {
             components_.erase(e);
         }
template<typename T > iterator entity::sparse_component_pool< T >::end ()
Definition at line 281 of file sparse_component_pool.hpp.
         {
             return iterator(components_.end());
         }
template<typename T > T* entity::sparse_component_pool< T >::get (entity e)
Definition at line 254 of file sparse_component_pool.hpp.
         {
             auto obj = components_.find(e);
             if(obj != components_.end())
             {
                 return &obj->second;
             }
             return nullptr;
         }
template<typename T > T const* entity::sparse_component_pool< T >::get (entity e) const
Definition at line 265 of file sparse_component_pool.hpp.
         {
             auto obj = components_.find(e);
             if(obj != components_.end())
             {
                 return &obj->second;
             }
             return nullptr;
         }
template<typename T > std::size_t entity::sparse_component_pool< T >::size ()
Definition at line 291 of file sparse_component_pool.hpp.
         {
             return components_.size();
         }
template<typename T > window entity::sparse_component_pool< T >::view ()
Definition at line 286 of file sparse_component_pool.hpp.
         {
             return window(components_.begin(), components_.end());
         }
Member Typedef Documentation
template<typename T > typedef iterator_impl entity::sparse_component_pool< T >::iterator
Definition at line 103 of file sparse_component_pool.hpp.
template<typename T > typedef T entity::sparse_component_pool< T >::type
Definition at line 102 of file sparse_component_pool.hpp.
Constructor & Destructor Documentation
template<typename T > entity::sparse_component_pool< T >::sparse_component_pool (entity_pool & owner_pool, T const & default_value = T())
Definition at line 161 of file sparse_component_pool.hpp.
References entity::entity_pool::begin(), entity::sparse_component_pool< T >::create(), entity::entity_pool::end(), entity::for_each(), entity::entity_pool::signal_list::on_entity_destroy, entity::entity_pool::signal_list::on_entity_swap, and entity::entity_pool::signals().
         {
         #if ENTITY_SUPPORT_VARIADICS
             auto create_func = &sparse_component_pool::create<T const&>;
         #else
             auto create_func = &sparse_component_pool::create;
         #endif
             // Create default values for existing entities.
             std::for_each(
                 owner_pool.begin(),
                 owner_pool.end(),
                 boost::bind(
                     create_func,
                     this,
                     ::_1,
                     boost::ref(default_value)
                 )
             );
             slots_.entity_destroy_handler =
                 owner_pool.signals().on_entity_destroy.connect(
                     boost::bind(
                         &sparse_component_pool::handle_destroy_entity,
                         this,
                         ::_1
                     )
                 )
             ;
             slots_.entity_swap_handler =
                 owner_pool.signals().on_entity_swap.connect(
                     boost::bind(
                         &sparse_component_pool::handle_swap_entity,
                         this,
                         ::_1,
                         ::_2
                     )
                 )
             ;
         }