entity: entity::component_creation_queue< ComponentPool > Singleton Reference
entity::component_creation_queue< ComponentPool > Singleton Reference
Description
template<typename ComponentPool>
singleton entity::component_creation_queue< ComponentPool >
Definition at line 28 of file component_creation_queue.hpp.
Public Types
typedef ComponentPool::type type
Public Member Functions
void clear ()
component_creation_queue (ComponentPool &p)
void flush ()
template<typename... Args>
void push (weak_entity e, Args &&...args)
~component_creation_queue ()
Member Function Documentation
template<typename ComponentPool > void entity::component_creation_queue< ComponentPool >::clear ()
Definition at line 63 of file component_creation_queue.hpp.
Referenced by entity::component_creation_queue< ComponentPool >::flush().
         {
             created_.clear();
         }
template<typename ComponentPool > void entity::component_creation_queue< ComponentPool >::flush ()
Definition at line 56 of file component_creation_queue.hpp.
References entity::component_creation_queue< ComponentPool >::clear().
Referenced by entity::component_creation_queue< ComponentPool >::~component_creation_queue().
         {
             std::sort(created_.begin(), created_.end());
             pool_.create_range(created_.begin(), created_.end());
             clear();
         }
template<typename ComponentPool > template<typename... Args> void entity::component_creation_queue< ComponentPool >::push (weak_entity e, Args &&... args)
Definition at line 45 of file component_creation_queue.hpp.
         {
             created_.push_back(std::make_pair(e, type(std::forward<Args>(args)...)));
         }
Member Typedef Documentation
template<typename ComponentPool > typedef ComponentPool::type entity::component_creation_queue< ComponentPool >::type
Definition at line 32 of file component_creation_queue.hpp.
Constructor & Destructor Documentation
template<typename ComponentPool > entity::component_creation_queue< ComponentPool >::component_creation_queue (ComponentPool & p)
Definition at line 34 of file component_creation_queue.hpp.
             : pool_(p)
         {}
template<typename ComponentPool > entity::component_creation_queue< ComponentPool >::~component_creation_queue ()
Definition at line 38 of file component_creation_queue.hpp.
References entity::component_creation_queue< ComponentPool >::flush().
         {
             flush();
         }