entity: entity::component::sparse_pool< T > Class Template Reference
entity::component::sparse_pool< T > Class Template Reference
Description
template<typename T>
class entity::component::sparse_pool< T >
Definition at line 55 of file sparse_pool.hpp.
Instances and minimal complete definitions
struct window
Friends
class creation_queue< sparse_pool< T > >
class destruction_queue< sparse_pool< T > >
Public Types
typedef iterator_impl iterator
typedef T type
Public Member Functions
template<typename... Args>
void auto_create_components (entity_pool &owner_pool, Args &&...constructor_args)
iterator begin ()
template<typename... Args>
T * create (entity e, Args &&...args)
void destroy (entity e)
iterator end ()
T * get (entity e)
T const * get (entity e) const
std::size_t size ()
sparse_pool (entity_pool &owner_pool, T const &default_value=T())
window view ()
Methods
template<typename T > friend class creation_queue< sparse_pool< T > > friend
Definition at line 303 of file sparse_pool.hpp.
template<typename T > friend class destruction_queue< sparse_pool< T > > friend
Definition at line 304 of file sparse_pool.hpp.
Member Function Documentation
template<typename T > template<typename... Args> void entity::component::sparse_pool< T >::auto_create_components (entity_pool & owner_pool, Args &&... constructor_args)
Definition at line 206 of file sparse_pool.hpp.
References entity::entity_pool::signal_list::on_entity_create, and entity::entity_pool::signals().
         {
             slots_.entity_create_handler =
                 owner_pool.signals().on_entity_create.connect(
                     std::function<void(entity)>(
                         [this, constructor_args...](entity e)
{
                             create(e, constructor_args...);
                         }
                     )
                 )
             ;
         }
template<typename T > iterator entity::component::sparse_pool< T >::begin ()
Definition at line 277 of file sparse_pool.hpp.
         {
             return iterator(components_.begin());
         }
template<typename T > template<typename... Args> T* entity::component::sparse_pool< T >::create (entity e, Args &&... args)
Definition at line 237 of file sparse_pool.hpp.
Referenced by entity::component::sparse_pool< T >::sparse_pool().
         {
             auto r = components_.emplace(e, std::forward<Args>(args)...);
             return &(r.first->second);
         }
template<typename T > void entity::component::sparse_pool< T >::destroy (entity e)
Definition at line 250 of file sparse_pool.hpp.
         {
             components_.erase(e);
         }
template<typename T > iterator entity::component::sparse_pool< T >::end ()
Definition at line 282 of file sparse_pool.hpp.
         {
             return iterator(components_.end());
         }
template<typename T > T* entity::component::sparse_pool< T >::get (entity e)
Definition at line 255 of file sparse_pool.hpp.
         {
             auto obj = components_.find(e);
             if(obj != components_.end())
             {
                 return &obj->second;
             }
             return nullptr;
         }
template<typename T > T const* entity::component::sparse_pool< T >::get (entity e) const
Definition at line 266 of file sparse_pool.hpp.
         {
             auto obj = components_.find(e);
             if(obj != components_.end())
             {
                 return &obj->second;
             }
             return nullptr;
         }
template<typename T > std::size_t entity::component::sparse_pool< T >::size ()
Definition at line 292 of file sparse_pool.hpp.
         {
             return components_.size();
         }
template<typename T > window entity::component::sparse_pool< T >::view ()
Definition at line 287 of file sparse_pool.hpp.
         {
             return window(components_.begin(), components_.end());
         }
Member Typedef Documentation
template<typename T > typedef iterator_impl entity::component::sparse_pool< T >::iterator
Definition at line 104 of file sparse_pool.hpp.
template<typename T > typedef T entity::component::sparse_pool< T >::type
Definition at line 103 of file sparse_pool.hpp.
Constructor & Destructor Documentation
template<typename T > entity::component::sparse_pool< T >::sparse_pool (entity_pool & owner_pool, T const & default_value = T())
Definition at line 162 of file sparse_pool.hpp.
References entity::entity_pool::begin(), entity::component::sparse_pool< T >::create(), entity::entity_pool::end(), entity::for_each(), entity::entity_pool::signal_list::on_entity_destroy, entity::entity_pool::signal_list::on_entity_swap, and entity::entity_pool::signals().
         {
         #if ENTITY_SUPPORT_VARIADICS
             auto create_func = &sparse_pool::create<T const&>;
         #else
             auto create_func = &sparse_pool::create;
         #endif
             // Create default values for existing entities.
             std::for_each(
                 owner_pool.begin(),
                 owner_pool.end(),
                 boost::bind(
                     create_func,
                     this,
                     ::_1,
                     boost::ref(default_value)
                 )
             );
             slots_.entity_destroy_handler =
                 owner_pool.signals().on_entity_destroy.connect(
                     boost::bind(
                         &sparse_pool::handle_destroy_entity,
                         this,
                         ::_1
                     )
                 )
             ;
             slots_.entity_swap_handler =
                 owner_pool.signals().on_entity_swap.connect(
                     boost::bind(
                         &sparse_pool::handle_swap_entity,
                         this,
                         ::_1,
                         ::_2
                     )
                 )
             ;
         }