entity: entity::component::saturated_pool< T > Class Template Reference
entity::component::saturated_pool< T > Class Template Reference
Description
template<typename T>
class entity::component::saturated_pool< T >
Definition at line 50 of file saturated_pool.hpp.
Instances and minimal complete definitions
struct entity_iterator
struct window
Friends
class creation_queue< saturated_pool< T > >
class destruction_queue< saturated_pool< T > >
Public Types
typedef iterator_impl iterator
typedef T type
Public Member Functions
template<typename... Args>
void auto_create_components (entity_pool &owner_pool, Args...constructor_args)
iterator begin ()
template<typename... Args>
T * create (entity e, Args &&...args)
void destroy (entity e)
iterator end ()
T * get (entity e)
T const * get (entity e) const
saturated_pool (entity_pool &owner_pool, T const &default_value=T())
std::size_t size ()
window view ()
Methods
template<typename T > friend class creation_queue< saturated_pool< T > > friend
Definition at line 323 of file saturated_pool.hpp.
template<typename T > friend class destruction_queue< saturated_pool< T > > friend
Definition at line 324 of file saturated_pool.hpp.
Member Function Documentation
template<typename T > template<typename... Args> void entity::component::saturated_pool< T >::auto_create_components (entity_pool & owner_pool, Args... constructor_args)
Definition at line 238 of file saturated_pool.hpp.
References entity::entity_pool::signal_list::on_entity_create, and entity::entity_pool::signals().
         {
             slots_.entity_create_handler =
                 owner_pool.signals().on_entity_create.connect(
                     std::function<void(entity)>(
                         [this, constructor_args...](entity e)
{
                             create(e, constructor_args...);
                         }
                     )
                 )
             ;
         }
template<typename T > iterator entity::component::saturated_pool< T >::begin ()
Definition at line 297 of file saturated_pool.hpp.
         {
             return iterator(this, 0);
         }
template<typename T > template<typename... Args> T* entity::component::saturated_pool< T >::create (entity e, Args &&... args)
Definition at line 269 of file saturated_pool.hpp.
         {
             components_.emplace(components_.begin() + e.index(), std::forward<Args>(args)...);
             return &components_[e.index()];
         }
template<typename T > void entity::component::saturated_pool< T >::destroy (entity e)
Definition at line 282 of file saturated_pool.hpp.
         {
             components_.erase(components_.begin() + e.index());
         }
template<typename T > iterator entity::component::saturated_pool< T >::end ()
Definition at line 302 of file saturated_pool.hpp.
         {
             return iterator(this, components_.size());
         }
template<typename T > T* entity::component::saturated_pool< T >::get (entity e)
Definition at line 287 of file saturated_pool.hpp.
         {
             return get_component(e);
         }
template<typename T > T const* entity::component::saturated_pool< T >::get (entity e) const
Definition at line 292 of file saturated_pool.hpp.
         {
             return get_component(e);
         }
template<typename T > std::size_t entity::component::saturated_pool< T >::size ()
Definition at line 312 of file saturated_pool.hpp.
         {
             return components_.size();
         }
template<typename T > window entity::component::saturated_pool< T >::view ()
Definition at line 307 of file saturated_pool.hpp.
         {
             return window(this);
         }
Member Typedef Documentation
template<typename T > typedef iterator_impl entity::component::saturated_pool< T >::iterator
Definition at line 105 of file saturated_pool.hpp.
template<typename T > typedef T entity::component::saturated_pool< T >::type
Definition at line 104 of file saturated_pool.hpp.
Constructor & Destructor Documentation
template<typename T > entity::component::saturated_pool< T >::saturated_pool (entity_pool & owner_pool, T const & default_value = T())
Definition at line 210 of file saturated_pool.hpp.
References entity::entity_pool::signal_list::on_entity_destroy, entity::entity_pool::signal_list::on_entity_swap, entity::entity_pool::signals(), and entity::entity_pool::size().
         {
             components_.resize(owner_pool.size(), default_value);
             slots_.entity_destroy_handler =
                 owner_pool.signals().on_entity_destroy.connect(
                     boost::bind(
                         &saturated_pool::handle_destroy_entity,
                         this,
                         ::_1
                     )
                 )
             ;
             slots_.entity_swap_handler =
                 owner_pool.signals().on_entity_swap.connect(
                     boost::bind(
                         &saturated_pool::handle_swap_entity,
                         this,
                         ::_1,
                         ::_2
                     )
                 )
             ;
         }