entity: entity::shared_entity Class Reference
entity::shared_entity Class Reference
Description
Definition at line 130 of file entity.hpp.
Friends
class entity_pool
void swap (shared_entity &, shared_entity &)
class weak_entity
Public Member Functions
void clear ()
entity get () const
bool operator< (shared_entity const &rhs) const
bool operator== (shared_entity const &rhs) const
shared_entity ()
shared_entity (unique_entity &&ref)
Methods
friend class entity_pool friend
Definition at line 163 of file entity.hpp.
void swap (shared_entity & a, shared_entity & b) friend
Definition at line 181 of file entity.hpp.
     {
         std::swap(a.ref_, b.ref_);
     }
friend class weak_entity friend
Definition at line 164 of file entity.hpp.
Member Function Documentation
void entity::shared_entity::clear ()
Definition at line 156 of file entity.hpp.
         {
             ref_ = nullptr;
         }
entity entity::shared_entity::get () const
Definition at line 141 of file entity.hpp.
References entity::make_entity().
Referenced by operator<(), and operator==().
         {
             return make_entity(*ref_);
         }
bool entity::shared_entity::operator< (shared_entity const & rhs) const
Definition at line 151 of file entity.hpp.
References get().
         {
             return get() < rhs.get();
         }
bool entity::shared_entity::operator== (shared_entity const & rhs) const
Definition at line 146 of file entity.hpp.
References get().
         {
             return get() == rhs.get();
         }
Constructor & Destructor Documentation
entity::shared_entity::shared_entity ()
Definition at line 134 of file entity.hpp.
         {}
entity::shared_entity::shared_entity (unique_entity && ref)
Definition at line 137 of file entity.hpp.
             : ref_(std::move(ref.ref_))
         {}