entity: entity::unique_entity Class Reference
entity::unique_entity Class Reference
Description
Definition at line 71 of file entity.hpp.
Friends
class entity_pool
class shared_entity
void swap (unique_entity &, unique_entity &)
Public Member Functions
void clear ()
entity get () const
bool operator< (unique_entity const &rhs) const
bool operator== (unique_entity const &rhs) const
unique_entity ()
Methods
friend class entity_pool friend
Definition at line 100 of file entity.hpp.
friend class shared_entity friend
Definition at line 101 of file entity.hpp.
void swap (unique_entity & a, unique_entity & b) friend
Definition at line 125 of file entity.hpp.
     {
         std::swap(a.ref_, b.ref_);
     }
Member Function Documentation
void entity::unique_entity::clear ()
Definition at line 93 of file entity.hpp.
         {
             ref_ = nullptr;
         }
entity entity::unique_entity::get () const
Definition at line 78 of file entity.hpp.
References entity::make_entity().
Referenced by operator<(), and operator==().
         {
             return make_entity(*ref_);
         }
bool entity::unique_entity::operator< (unique_entity const & rhs) const
Definition at line 88 of file entity.hpp.
References get().
         {
             return get() < rhs.get();
         }
bool entity::unique_entity::operator== (unique_entity const & rhs) const
Definition at line 83 of file entity.hpp.
References get().
         {
             return get() == rhs.get();
         }
Constructor & Destructor Documentation
entity::unique_entity::unique_entity ()
Definition at line 75 of file entity.hpp.
         {}