entity: entity::component::dense_pool< T > Class Template Reference
entity::component::dense_pool< T > Class Template Reference
Description
template<typename T>
class entity::component::dense_pool< T >
Definition at line 53 of file dense_pool.hpp.
Instances and minimal complete definitions
struct window
Friends
class creation_queue< dense_pool< T > >
class destruction_queue< dense_pool< T > >
Public Types
typedef iterator_impl iterator
typedef T type
Public Member Functions
template<typename... Args>
void auto_create_components (entity_pool &owner_pool, Args &&...constructor_args)
iterator begin ()
template<typename... Args>
T * create (entity e, Args &&...args)
dense_pool (entity_pool &owner_pool, T const &default_value=T())
void destroy (entity e)
iterator end ()
T * get (entity e)
T const * get (entity e) const
std::size_t size ()
window view ()
Methods
template<typename T > friend class creation_queue< dense_pool< T > > friend
Definition at line 352 of file dense_pool.hpp.
template<typename T > friend class destruction_queue< dense_pool< T > > friend
Definition at line 353 of file dense_pool.hpp.
Member Function Documentation
template<typename T > template<typename... Args> void entity::component::dense_pool< T >::auto_create_components (entity_pool & owner_pool, Args &&... constructor_args)
Definition at line 244 of file dense_pool.hpp.
References entity::entity_pool::signal_list::on_entity_create, and entity::entity_pool::signals().
         {
             slots_.entity_create_handler =
                 owner_pool.signals().on_entity_create.connect(
                     std::function<void(entity)>(
                         [this, constructor_args...](entity e)
{
                             create_entity_slot(e);
                             create(e, constructor_args...);
                         }
                     )
                 )
             ;
         }
template<typename T > iterator entity::component::dense_pool< T >::begin ()
Definition at line 326 of file dense_pool.hpp.
         {
             return iterator(this, 0);
         }
template<typename T > template<typename... Args> T* entity::component::dense_pool< T >::create (entity e, Args &&... args)
Definition at line 277 of file dense_pool.hpp.
Referenced by entity::component::dense_pool< T >::dense_pool().
         {
             set_available(e.index(), false);
             T* ret_val = get_component(e.index());
             new(ret_val) T(std::forward<Args>(args)...);
             ++used_count_;
             return ret_val;
         }
template<typename T > void entity::component::dense_pool< T >::destroy (entity e)
Definition at line 296 of file dense_pool.hpp.
         {
             BOOST_ASSERT(!is_available(e.index()) && "Trying to destroy un-allocated component.");
             --used_count_;
             T* p = get_component(e.index());
             p->~T();
             set_available(e.index(), true);
         }
template<typename T > iterator entity::component::dense_pool< T >::end ()
Definition at line 331 of file dense_pool.hpp.
         {
             return iterator(this, available_.size());
         }
template<typename T > T* entity::component::dense_pool< T >::get (entity e)
Definition at line 306 of file dense_pool.hpp.
         {
             if(is_available(e.index()))
             {
                 return nullptr;
             }
             return get_component(e.index());
         }
template<typename T > T const* entity::component::dense_pool< T >::get (entity e) const
Definition at line 316 of file dense_pool.hpp.
         {
             if(is_available(e.index()))
             {
                 return nullptr;
             }
             return get_component(e.index());
         }
template<typename T > std::size_t entity::component::dense_pool< T >::size ()
Definition at line 341 of file dense_pool.hpp.
         {
             return used_count_;
         }
template<typename T > window entity::component::dense_pool< T >::view ()
Definition at line 336 of file dense_pool.hpp.
         {
             return window(this);
         }
Member Typedef Documentation
template<typename T > typedef iterator_impl entity::component::dense_pool< T >::iterator
Definition at line 127 of file dense_pool.hpp.
template<typename T > typedef T entity::component::dense_pool< T >::type
Definition at line 126 of file dense_pool.hpp.
Constructor & Destructor Documentation
template<typename T > entity::component::dense_pool< T >::dense_pool (entity_pool & owner_pool, T const & default_value = T())
Definition at line 186 of file dense_pool.hpp.
References entity::entity_pool::begin(), entity::component::dense_pool< T >::create(), entity::entity_pool::end(), entity::for_each(), entity::entity_pool::signal_list::on_entity_create, entity::entity_pool::signal_list::on_entity_destroy, entity::entity_pool::signal_list::on_entity_swap, entity::entity_pool::signals(), and entity::entity_pool::size().
             : used_count_(0)
         {
             components_.resize(owner_pool.size());
             available_.resize(owner_pool.size(), true);
         #if ENTITY_SUPPORT_VARIADICS
             auto create_func = &dense_pool::create<T const&>;
         #else
             auto create_func = &dense_pool::create;
         #endif
             // Create default values for existing entities.
             std::for_each(
                 owner_pool.begin(),
                 owner_pool.end(),
                 boost::bind(
                     create_func,
                     this,
                     ::_1,
                     boost::ref(default_value)
                 )
             );
             slots_.entity_create_handler =
                 owner_pool.signals().on_entity_create.connect(
                     boost::bind(
                         &dense_pool::handle_create_entity,
                         this,
                         ::_1
                     )
                 )
             ;
             slots_.entity_destroy_handler =
                 owner_pool.signals().on_entity_destroy.connect(
                     boost::bind(
                         &dense_pool::handle_destroy_entity,
                         this,
                         ::_1
                     )
                 )
             ;
             slots_.entity_swap_handler =
                 owner_pool.signals().on_entity_swap.connect(
                     boost::bind(
                         &dense_pool::handle_swap_entity,
                         this,
                         ::_1,
                         ::_2
                     )
                 )
             ;
         }