entity: entity Namespace Reference
entity Namespace Reference
Namespaces
detail
functional
iterator_traits
simd
Classes
singleton component_creation_queue
singleton component_destruction_queue
class dense_component_pool
class entity
class entity_incremental_iterator
class entity_pool
class entity_range
class entity_skipping_iterator
struct is_zipped_component_tuple
struct is_zipped_component_tuple< zipped_component_windows< ComponentTuple > >
class saturated_component_pool
class shared_entity
class sparse_component_pool
class unique_entity
class weak_entity
class zipped_component_windows
Typedefs
typedef std::size_t entity_index_t
Functions
template<typename Iterator , typename EndIterator >
Iterator begin (entity_range< Iterator, EndIterator > &r)
entity_pool::iterator begin (entity_pool const &p)
template<typename Iterator , typename EndIterator >
EndIterator end (entity_range< Iterator, EndIterator > &r)
entity_pool::iterator end (entity_pool const &p)
template<typename EntityList , typename ComponentPoolTuple , typename Fn >
void for_each (EntityList const &entities, ComponentPoolTuple &&p, iterator_traits::is_incremental_tag, Fn f)
template<typename EntityList , typename ComponentPoolTuple , typename Fn >
void for_each (EntityList const &entities, ComponentPoolTuple &&p, iterator_traits::is_skipping_tag, Fn f)
template<typename EntityList , typename ComponentPoolTuple , typename Fn >
void for_each (EntityList const &entities, ComponentPoolTuple &&p, Fn f)
template<std::size_t idx, typename ZippedComponentWindows >
std::enable_if
< is_zipped_component_tuple
< ZippedComponentWindows >
::value, typename
boost::fusion::result_of::value_at_c
< typename
ZippedComponentWindows::windows_type,
idx >::type::value_type & >
::type get (ZippedComponentWindows const &windows)
entity make_entity (entity_index_t idx) BOOST_NOEXCEPT_OR_NOTHROW
template<typename EntityList , typename ZippedComponentWindows >
auto make_entity_begin (iterator_traits::is_skipping_tag, EntityList const &entities, ZippedComponentWindows windows) -> entity_skipping_iterator< decltype(begin(entities)), ZippedComponentWindows >
template<typename EntityList , typename ZippedComponentWindows >
auto make_entity_begin (iterator_traits::is_incremental_tag, EntityList const &entities, ZippedComponentWindows windows) -> entity_incremental_iterator< decltype(entities.begin()), ZippedComponentWindows >
template<typename EntityList , typename ZippedComponentWindows >
auto make_entity_begin (EntityList const &list, ZippedComponentWindows windows) -> decltype(make_entity_begin(iterator_traits::entity_list_is_incremental< EntityList >(), list, windows))
template<typename EntityList , typename ZippedComponentWindows >
auto make_entity_end (iterator_traits::is_skipping_tag, EntityList const &entities, ZippedComponentWindows windows) -> entity_skipping_iterator< decltype(end(entities)), ZippedComponentWindows >
template<typename EntityList , typename ZippedComponentWindows >
auto make_entity_end (iterator_traits::is_incremental_tag, EntityList &entities, ZippedComponentWindows windows) -> entity_incremental_iterator< decltype(entities.end()), ZippedComponentWindows >
template<typename EntityList , typename ZippedComponentWindows >
auto make_entity_end (EntityList const &list, ZippedComponentWindows windows) -> decltype(make_entity_end(iterator_traits::entity_list_is_incremental< EntityList >(), list, windows))
template<typename EntityList , typename ZippedComponentWindows >
auto make_entity_range (EntityList const &list, ZippedComponentWindows windows) -> entity_range< decltype(make_entity_begin(list, windows)), decltype(make_entity_end(list, windows))>
void swap (unique_entity &a, unique_entity &b)
void swap (shared_entity &a, shared_entity &b)
template<typename... Pools>
boost::fusion::vector< Pools &...> tie (Pools &...pools)
template<typename... Pools>
auto zip (Pools &...pools) -> decltype(zip_from_tuple(tie(pools...)))
template<typename ComponentPoolTuple >
zipped_component_windows
< ComponentPoolTuple > zip_from_tuple (ComponentPoolTuple pools)
Variables
iterator_traits::is_incremental_tag
const incremental {}
iterator_traits::is_skipping_tag
const skipping {}
Typedef Documentation
typedef std::size_t entity::entity_index_t
Definition at line 24 of file entity_index.hpp.
Function Documentation
template<typename Iterator , typename EndIterator > Iterator entity::begin (entity_range< Iterator, EndIterator > & r)
Definition at line 173 of file entity_range.hpp.
References entity::entity_range< Iterator, EndIterator >::begin().
     {
         return r.begin();
     }
entity_pool::iterator entity::begin (entity_pool const & p)
Definition at line 246 of file entity_pool.hpp.
References entity::entity_pool::begin().
Referenced by for_each(), make_entity_begin(), and make_entity_end().
     {
         return p.begin();
     }
template<typename Iterator , typename EndIterator > EndIterator entity::end (entity_range< Iterator, EndIterator > & r)
Definition at line 179 of file entity_range.hpp.
References entity::entity_range< Iterator, EndIterator >::end().
     {
         return r.end();
     }
entity_pool::iterator entity::end (entity_pool const & p)
Definition at line 251 of file entity_pool.hpp.
References entity::entity_pool::end().
Referenced by for_each(), make_entity_begin(), and make_entity_end().
     {
         return p.end();
     }
template<typename EntityList , typename ComponentPoolTuple , typename Fn > void entity::for_each (EntityList const & entities, ComponentPoolTuple && p, iterator_traits::is_incremental_tag , Fn f)
Definition at line 37 of file for_each.hpp.
References begin(), end(), and entity::simd::detail::invoke().
Referenced by entity::dense_component_pool< T >::dense_component_pool(), for_each(), and entity::sparse_component_pool< T >::sparse_component_pool().
     {
         auto i = begin(entities);
         auto e = end(entities);
         auto c = boost::fusion::as_vector(
             boost::fusion::transform(
             std::forward<ComponentPoolTuple>(p),
             functional::get_window()
             )
         );
         if(i != e)
         {
             if(boost::fusion::all(c, functional::is_entity(*i)))
             {
                 boost::fusion::invoke(
                     f,
                     boost::fusion::transform(c, functional::get_component())
                 );
             }
             ++i;
         }
         for(; i != e; ++i)
         {
             if(boost::fusion::fold(c, true, functional::increment_window(*i)))
             {
                 boost::fusion::invoke(
                     f,
                     boost::fusion::transform(c, functional::get_component())
                 );
             }
         }
     }
template<typename EntityList , typename ComponentPoolTuple , typename Fn > void entity::for_each (EntityList const & entities, ComponentPoolTuple && p, iterator_traits::is_skipping_tag , Fn f)
Definition at line 77 of file for_each.hpp.
References begin(), end(), and entity::simd::detail::invoke().
     {
         auto i = begin(entities);
         auto e = end(entities);
         auto c = boost::fusion::as_vector(
             boost::fusion::transform(
             std::forward<ComponentPoolTuple>(p),
             functional::get_window()
             )
         );
         if(i != e)
         {
             if(boost::fusion::all(c, functional::is_entity(*i)))
             {
                 boost::fusion::invoke(
                     f,
                     boost::fusion::transform(c, functional::get_component())
                 );
             }
             ++i;
         }
         for(; i != e; ++i)
         {
             if(boost::fusion::fold(c, true, functional::advance_window(*i)))
             {
                 boost::fusion::invoke(
                     f,
                     boost::fusion::transform(c, functional::get_component())
                 );
             }
         }
     }
template<typename EntityList , typename ComponentPoolTuple , typename Fn > void entity::for_each (EntityList const & entities, ComponentPoolTuple && p, Fn f)
Definition at line 115 of file for_each.hpp.
References for_each().
     {
         for_each(entities, p, iterator_traits::entity_list_is_incremental<EntityList>(), f);
     }
template<std::size_t idx, typename ZippedComponentWindows > std::enable_if< is_zipped_component_tuple<ZippedComponentWindows>::value, typename boost::fusion::result_of::value_at_c< typename ZippedComponentWindows::windows_type, idx >::type::value_type& >::type entity::get (ZippedComponentWindows const & windows)
Definition at line 169 of file zip.hpp.
     {
         return boost::fusion::at_c<idx>(windows.get()).get();
     }
entity entity::make_entity (entity_index_t idx)
Definition at line 64 of file entity.hpp.
Referenced by entity::entity_pool::create(), entity::entity_pool::create_unique(), entity::unique_entity::get(), entity::shared_entity::get(), and entity::entity_pool::~entity_pool().
     {
         return entity(idx);
     }
template<typename EntityList , typename ZippedComponentWindows > auto entity::make_entity_begin (iterator_traits::is_skipping_tag , EntityList const & entities, ZippedComponentWindows windows) -> entity_skipping_iterator< decltype(begin(entities)), ZippedComponentWindows>
Definition at line 187 of file entity_range.hpp.
References begin(), and end().
Referenced by make_entity_begin(), and make_entity_range().
     {
         return entity_skipping_iterator<
             decltype(begin(entities)),
             ZippedComponentWindows
         >(begin(entities), end(entities), std::move(windows));
     }
template<typename EntityList , typename ZippedComponentWindows > auto entity::make_entity_begin (iterator_traits::is_incremental_tag , EntityList const & entities, ZippedComponentWindows windows) -> entity_incremental_iterator< decltype(entities.begin()), ZippedComponentWindows>
Definition at line 211 of file entity_range.hpp.
     {
         return entity_incremental_iterator<
             decltype(entities.begin()),
             ZippedComponentWindows
         >(entities.begin(), entities.end(), std::move(windows));
     }
template<typename EntityList , typename ZippedComponentWindows > auto entity::make_entity_begin (EntityList const & list, ZippedComponentWindows windows) -> decltype(make_entity_begin(iterator_traits::entity_list_is_incremental<EntityList>(), list, windows))
Definition at line 235 of file entity_range.hpp.
References make_entity_begin().
     {
         return make_entity_begin(
             iterator_traits::entity_list_is_incremental<EntityList>(),
             list,
             std::move(windows)
         );
     }
template<typename EntityList , typename ZippedComponentWindows > auto entity::make_entity_end (iterator_traits::is_skipping_tag , EntityList const & entities, ZippedComponentWindows windows) -> entity_skipping_iterator< decltype(end(entities)), ZippedComponentWindows>
Definition at line 198 of file entity_range.hpp.
References begin(), and end().
Referenced by make_entity_end(), and make_entity_range().
     {
         return entity_skipping_iterator<
             decltype(begin(entities)),
             ZippedComponentWindows
         >(end(entities), end(entities), std::move(windows));
     }
template<typename EntityList , typename ZippedComponentWindows > auto entity::make_entity_end (iterator_traits::is_incremental_tag , EntityList & entities, ZippedComponentWindows windows) -> entity_incremental_iterator< decltype(entities.end()), ZippedComponentWindows>
Definition at line 222 of file entity_range.hpp.
     {
         return entity_incremental_iterator<
             decltype(entities.begin()),
             ZippedComponentWindows
         >(entities.end(), entities.end(), std::move(windows));
     }
template<typename EntityList , typename ZippedComponentWindows > auto entity::make_entity_end (EntityList const & list, ZippedComponentWindows windows) -> decltype(make_entity_end(iterator_traits::entity_list_is_incremental<EntityList>(), list, windows))
Definition at line 245 of file entity_range.hpp.
References make_entity_end().
     {
         return make_entity_end(
             iterator_traits::entity_list_is_incremental<EntityList>(),
             list,
             std::move(windows)
         );
     }
template<typename EntityList , typename ZippedComponentWindows > auto entity::make_entity_range (EntityList const & list, ZippedComponentWindows windows) -> entity_range<decltype(make_entity_begin(list, windows)), decltype(make_entity_end(list, windows))>
Definition at line 257 of file entity_range.hpp.
References make_entity_begin(), and make_entity_end().
     {
         return entity_range<
             decltype(make_entity_begin(list, windows)),
             decltype(make_entity_end(list, windows))>(
                 make_entity_begin(list, windows),
                 make_entity_end(list, windows)
             )
         ;
     }
void entity::swap (unique_entity & a, unique_entity & b)
Definition at line 125 of file entity.hpp.
References swap().
     {
         std::swap(a.ref_, b.ref_);
     }
void entity::swap (shared_entity & a, shared_entity & b)
Definition at line 181 of file entity.hpp.
Referenced by swap().
     {
         std::swap(a.ref_, b.ref_);
     }
template<typename... Pools> boost::fusion::vector<Pools&...> entity::tie (Pools &... pools)
Definition at line 28 of file tie.hpp.
Referenced by zip().
     {
         return boost::fusion::vector<Pools&...>(pools...);
     }
template<typename... Pools> auto entity::zip (Pools &... pools) -> decltype(zip_from_tuple(tie(pools...)))
Definition at line 186 of file zip.hpp.
References tie(), and zip_from_tuple().
     {
         return zip_from_tuple(tie(pools...));
     }
template<typename ComponentPoolTuple > zipped_component_windows<ComponentPoolTuple> entity::zip_from_tuple (ComponentPoolTuple pools)
Definition at line 175 of file zip.hpp.
Referenced by zip().
     {
         return zipped_component_windows<
             ComponentPoolTuple
         >(std::move(pools));
     }
Variable Documentation
iterator_traits::is_incremental_tag const entity::incremental {}
Definition at line 31 of file iterator_traits.hpp.
iterator_traits::is_skipping_tag const entity::skipping {}
Definition at line 32 of file iterator_traits.hpp.