entity: entity::entity_pool::signal_list Struct Reference
entity::entity_pool::signal_list Struct Reference
Description
Definition at line 90 of file entity_pool.hpp.
Public Attributes
boost::signals2::signal< void(entity)> on_entity_create
boost::signals2::signal< void(entity)> on_entity_destroy
boost::signals2::signal< void(entity, entity)> on_entity_swap
Member Data Documentation
boost::signals2::signal<void(entity)> entity::entity_pool::signal_list::on_entity_create
Definition at line 92 of file entity_pool.hpp.
Referenced by entity::component::sparse_pool< T >::auto_create_components(), entity::component::saturated_pool< T >::auto_create_components(), entity::component::dense_pool< T >::auto_create_components(), entity::entity_pool::create(), entity::entity_pool::create_unique(), and entity::component::dense_pool< T >::dense_pool().
boost::signals2::signal<void(entity)> entity::entity_pool::signal_list::on_entity_destroy
Definition at line 93 of file entity_pool.hpp.
Referenced by entity::component::dense_pool< T >::dense_pool(), entity::component::saturated_pool< T >::saturated_pool(), and entity::component::sparse_pool< T >::sparse_pool().
boost::signals2::signal<void(entity, entity)> entity::entity_pool::signal_list::on_entity_swap
Definition at line 94 of file entity_pool.hpp.
Referenced by entity::component::dense_pool< T >::dense_pool(), entity::component::saturated_pool< T >::saturated_pool(), and entity::component::sparse_pool< T >::sparse_pool().